// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Answer struct {
	ID        int64     `json:"id"`
	AnswerID  int32     `json:"answer_id"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"created_at"`
}

type Blog struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	Text      string    `json:"text"`
	Image     []byte    `json:"image"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Question struct {
	ID        int64     `json:"id"`
	Text      string    `json:"text"`
	AnswerID  int64     `json:"answer_id"`
	CreatedAt time.Time `json:"created_at"`
}
